### ISSUE TITLE
Feat: 설정 탭 구현

### ISSUE THREAD

**Issue by dev-junehee** [dev-junehee/me-time#12]
##  📌 Overview
- 설정 탭 화면을 구현합니다.

<br />

## ✔️ Todo
- [x] 계정 삭제 (UserDefaults, Realm 초기화) -> 온보딩 전환
- [x] 데이터 전체 삭제
- [x] 현재 버전 공유
- [x] 개발자 이메일 연결
