### ISSUE TITLE
Feat: 음악 추천 탭 구현

### ISSUE THREAD

**Issue by dev-junehee** [dev-junehee/me-time#15]
##  📌 Overview
- 음악 추천 탭을 구현합니다.

<br />

## ✔️ Todo
- [x] YouTube API 연결
- [x] 음악 추천 리스트 구현
- [x] 추천 리스트 클릭 시 디테일 화면 전환 (WebView)

<br />

## 🔗 References
- [YouTube Data API](https://developers.google.com/youtube/v3/getting-started?hl=ko)
- [[Swift] Youtube API 활용하여 앱 만들기 (1) : Youtube API 사용방법](https://velog.io/@anfgbwl/Swift-Youtube-API-활용하여-앱-만들기-1-Youtube-API-사용방법)
- [[API] Youtube 데이터 가져오기](https://trond-soo.tistory.com/117)
- [[iOS] SwiftUI 사용하여 WebView 띄우기](https://velog.io/@dbqls200/iOS-SwiftUI-사용하여-WebView-띄우기)
- [SwiftUI - Page banner 만들기](https://velog.io/@whale/SwiftUI-Page-banner-만들기)
- [Using SwiftUI’s AsyncImage to render remote images from URLs](https://wwdcbysundell.com/2021/using-swiftui-async-image/)

<br />

### SwiftUI AsyncImage Resizable 안 되는 이슈

- 수정 전

```swift
AsyncImage(url: URL(string: item.snippet.thumbnails.medium.url)
   .frame(width: 320, height: 180)
```

- 수정 후

```swift
AsyncImage(url: URL(string: item.snippet.thumbnails.medium.url)) { image in
    image
        .resizable()
        .aspectRatio(contentMode: .fill)
        .frame(height: 250)
} placeholder: {
    ProgressView()
}
```
